name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "hakimihope3"
          git config user.email "hakimihope3@gmail.com"

      - name: Add Upstream
        run: git remote add upstream https://github.com/lyfe00011/levanter.git

      - name: Fetch and Merge
        run: |
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
